name: Sorbet
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sorbet:
    name: Sorbet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0 # v1.197.0
        with:
          bundler-cache: true

      - run: bundle exec tapioca gem --verify

      - run: bundle exec srb tc

      - run: bundle exec spoom srb coverage

      - run: |
          bundle exec spoom srb bump --from=false --to=true --dry
          bundle exec spoom srb bump --from=true --to=strict --dry
          bundle exec spoom srb bump --from=strict --to=strong --dry

      - run: bundle exec spoom srb coverage snapshot --save

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: spoom_data
          path: ./spoom_data/

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./script/generate-coverage-report
        env:
          GH_TOKEN: ${{ github.token }}

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: spoom_report
          path: ./spoom_report.html
